BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE company CASCADE CONSTRAINTS'; 		
	EXECUTE IMMEDIATE 'DROP TABLE company PURGE'; 	
	EXCEPTION WHEN OTHERS THEN NULL;
END;
/

create table company(
	comp_id			number NOT NULL,
	name			varchar(100) NOT NULL,	
	primary_sector	varchar(100) NOT NULL,
	website			varchar(100) NOT NULL,
	primary key (comp_id)
);

INSERT INTO company (comp_id,name,primary_sector,website) VALUES (6,'A Neque Industries','oil','cursus luctus,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (40,'Mollis PC','service','ut odio');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (46,'Fringilla Corporation','oil','amet, consectetuer');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (5,'Vivamus Industries','mining','lobortis ultrices.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (21,'Amet Consectetuer Adipiscing Associates','education','feugiat non,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (42,'Metus In Nec Corp.','entertainment','laoreet ipsum.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (40,'Egestas Institute','mining','feugiat. Sed');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (45,'Mus Corporation','tourism','cursus et,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (39,'Adipiscing Fringilla Porttitor LLC','tourism','Quisque porttitor');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (28,'Diam Nunc Ullamcorper Corporation','tourism','pharetra sed,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (46,'Donec Nibh Quisque Institute','mining','Nulla facilisis.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (3,'Nec Imperdiet Nec Incorporated','technology','ac ipsum.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (9,'Sit Ltd','entertainment','pharetra ut,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (15,'Vehicula Aliquet Libero Limited','technology','quis urna.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (17,'Fusce Feugiat Lorem LLP','mining','lacus, varius');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (30,'Nisi Cum Sociis Incorporated','oil','Donec elementum,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (50,'Nec LLC','oil','Cras sed');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (28,'Ridiculus Mus Proin Incorporated','service','tincidunt. Donec');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (36,'Et Magnis PC','tourism','auctor, velit');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (12,'Mauris Suspendisse Corporation','oil','at sem');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (9,'Morbi Inc.','tourism','sodales purus,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (35,'Dui Augue Eu Ltd','education','tincidunt, neque');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (9,'Dui Suspendisse Institute','tourism','sapien. Nunc');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (9,'Nisl Elementum Purus Consulting','mining','sed, est.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (9,'Hendrerit Consectetuer Corp.','entertainment','mattis velit');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (39,'Tortor Nunc PC','tourism','condimentum. Donec');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (38,'Blandit At Institute','tourism','eget, venenatis');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (38,'Pede Consulting','education','Proin eget');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (34,'Amet Faucibus Ut Company','mining','scelerisque mollis.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (32,'Consectetuer Adipiscing Elit LLP','oil','amet ornare');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (35,'Sit Amet Ultricies Corp.','oil','Aliquam erat');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (18,'Libero Corporation','mining','cursus a,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (11,'Arcu Curabitur Limited','mining','Vivamus nibh');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (32,'Convallis Est Industries','mining','ante dictum');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (6,'Quisque Nonummy Foundation','service','scelerisque dui.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (25,'Ac Mattis LLC','education','enim consequat');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (22,'Imperdiet Ullamcorper Duis Consulting','service','sodales nisi');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (20,'Aliquam Corp.','tourism','urna et');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (49,'Velit Associates','tourism','Sed congue,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (50,'Diam Vel Corp.','education','lorem ac');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (31,'Nulla Donec Consulting','tourism','vulputate, nisi');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (47,'Nullam Nisl Maecenas Associates','service','enim commodo');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (25,'Eget Metus Eu LLC','service','mi, ac');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (12,'Mauris Vel Turpis Company','education','egestas. Aliquam');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (28,'Eu Eleifend Nec LLP','entertainment','id enim.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (11,'Ornare Placerat Institute','mining','ultricies ligula.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (50,'Sem Corporation','education','Sed malesuada');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (30,'Nec Imperdiet Incorporated','service','semper, dui');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (43,'Nullam Corp.','tourism','a, malesuada');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (38,'Vulputate Nisi Corp.','tourism','sodales at,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (46,'Risus In Mi Company','entertainment','molestie dapibus');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (23,'Maecenas Mi Felis Company','oil','tristique pellentesque,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (45,'Natoque Penatibus Et Consulting','entertainment','lectus pede');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (5,'Lorem Auctor Quis Company','education','sapien. Nunc');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (36,'Pede Nunc Institute','entertainment','pellentesque, tellus');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (1,'Auctor Ullamcorper Nisl Consulting','service','egestas a,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (3,'Nulla Eu Neque Ltd','oil','Pellentesque ultricies');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (18,'Ultrices Iaculis Odio Industries','mining','molestie in,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (36,'Quis Associates','education','laoreet, libero');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (27,'Eget Lacus Mauris Corporation','technology','mi lacinia');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (36,'In Limited','entertainment','mi. Aliquam');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (31,'Ac Incorporated','technology','nec, diam.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (41,'Egestas A LLC','service','amet, consectetuer');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (26,'Eu Erat Consulting','tourism','tincidunt, nunc');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (1,'Ante Limited','service','nulla magna,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (18,'Aenean Egestas Hendrerit Consulting','service','mattis semper,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (22,'Magna Sed Institute','entertainment','mollis. Phasellus');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (4,'Dolor Nonummy Limited','service','nec, leo.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (4,'A Auctor Non Corp.','entertainment','quam dignissim');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (25,'Suspendisse Eleifend Cras PC','oil','non arcu.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (26,'Sodales Nisi Consulting','entertainment','varius orci,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (26,'Elit Dictum Eu Incorporated','entertainment','tellus sem');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (42,'Hendrerit Consulting','technology','in sodales');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (43,'Etiam Laoreet Incorporated','technology','mauris eu');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (51,'Arcu Iaculis Enim Corp.','education','Aliquam erat');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (39,'Arcu Nunc Mauris Foundation','education','egestas. Aliquam');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (28,'Commodo Tincidunt Nibh Associates','mining','orci lobortis');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (23,'Lorem LLP','entertainment','mollis lectus');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (8,'Ornare Sagittis LLC','education','Praesent interdum');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (2,'Nulla Incorporated','tourism','vitae, posuere');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (35,'Interdum LLC','tourism','magnis dis');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (17,'Fermentum PC','technology','id, ante.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (46,'Taciti Sociosqu LLP','entertainment','augue scelerisque');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (5,'Ultricies Corporation','tourism','massa. Integer');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (42,'Id Nunc Interdum Corp.','entertainment','sit amet,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (31,'Ligula Nullam Feugiat LLC','entertainment','adipiscing elit.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (27,'Luctus Sit Amet Corp.','tourism','Ut semper');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (1,'Praesent Luctus Curabitur Company','technology','dictum sapien.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (45,'Malesuada Ut Sem Company','technology','diam lorem,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (1,'Maecenas Malesuada Fringilla Institute','oil','at pede.');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (22,'Mi Foundation','technology','convallis erat,');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (44,'Feugiat Inc.','oil','Praesent eu');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (49,'Ornare Consulting','mining','lacus. Mauris');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (19,'Tristique Ac Eleifend Limited','oil','vel quam');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (5,'Eu Corp.','oil','ac, feugiat');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (9,'Sagittis Duis Gravida Corporation','service','nec, mollis');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (39,'Consectetuer Inc.','oil','tellus non');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (15,'Urna Convallis Company','entertainment','purus. Maecenas');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (15,'Pharetra Nam Ac LLC','technology','urna. Vivamus');
INSERT INTO company (comp_id,name,primary_sector,website) VALUES (20,'Sapien Corporation','education','sem semper');
